### ISSUE TITLE
No matching distribution found for urllib

### ISSUE THREAD

**Issue by kaiorafael** [hposton/python-for-cybersecurity#1]
By running the command 

`python -m pip install -r req.txt`

I am getting the following with Python 3.9 env:
```
ERROR: Could not find a version that satisfies the requirement urllib (from versions: none)
ERROR: No matching distribution found for urllib
```

So, _urllib_ is already a standard Python library.  I was able to install the required libraries after I have removed _urllib_

asyncssh
brython
dnspython
httpserver
libratom
paramiko
psutil
pycryptodomex
pyinstaller
requests
scapy
wmi

**Comment by hposton** [comment]
Yeah, that was a stupid mistake.  Thanks for catching!
