### ISSUE TITLE
Issue with Test Default Credentials

### ISSUE THREAD

**Issue by nslybb** [hposton/python-for-cybersecurity#5]
Hello, when I try to run the code you provided in "test_default_creds.py" I get this error that I am not able to solve.
I tried to run as admin with sudo but it still doesn't work. Do you know what I have to do? I have to say that I am very inexperienced in this stuff so maybe it is simpler than I thought. 
![Screenshot 2023-07-04 13 38 01](https://github.com/hposton/python-for-cybersecurity/assets/138580804/4e1df110-93fc-49e5-9c31-015ed2a8ef62)

**Comment by nslybb** [comment]
Update:
I try to help myself with the internet with no success. As last try, I tried to copy the code that was shown in the video (which is a little different that the one provided on github section 3.1) and I got this errors as a result. If I have understood correctly, it is an issue related to the connection with the Telnet server. Any advice? At this point the solution is beyond me. 
![Screenshot 2023-07-09 12 55 50](https://github.com/hposton/python-for-cybersecurity/assets/138580804/9bfeb2a3-ba2e-48f4-ae23-b6098732ec1f)

**Comment by hposton** [comment]
Hey, this code assumes that the system it's running on it actually running a telnet server that it can test usernames/passwords on. Judging by this error, your lab machine isn't running a Telnet server. This is why the computer would refuse a connection on the Telnet port
