### ISSUE TITLE
Issue with Autorun Scripts

### ISSUE THREAD

**Issue by nslybb** [hposton/python-for-cybersecurity#6]
Hello, 
I had this problem with the code you put on Git Hub "USB.py". 
Also, how can I "import" into python the Firefox icon? I mean, usually I'm using nano to save the codes you provide to us and then run them, but I don't know how to (and if I am suppose to) do it with images.
Thanks a lot!
![Uploading USB.pyERR.png…]()

**Comment by hposton** [comment]
The firefox icon file just needs to be in the same directory. You can see it referenced in the call to PyInstaller, which is what uses it.

**Comment by nslybb** [comment]
The main problem is that it says "No such file or directory: '__pycache__' and I can't fix it. I just discovered that I didn't upload correctly the screenshot. 
![USB pyERR](https://github.com/hposton/python-for-cybersecurity/assets/138580804/d1d3606b-ab59-45b3-94ce-fda626beb31e)

**Comment by nslybb** [comment]
The only progress I made is that before the traceback things I have obtained the "EXE created".
